### ISSUE TITLE
db schema

### ISSUE THREAD

**Issue by iambernics** [PauloFDO/ParkingManagement#1]
Hello Paulo,

What is the easiest way to create the DB scheme for the application?

Regards,
Gabor

 ```
 Application startup exception
System.AggregateException: One or more errors occurred. (Invalid object name 'AspNetUsers'.)
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid object name 'AspNetUsers'.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)

```

**Comment by PauloFDO** [comment]
Hey Bernics! Sorry for the lack of detail, I created this repository as portfolio for my current job, never expected anyone to actually be interested!

This is using entity framework, the database would be created with the command "update-database" in the package manager console (make sure it is pointing to the Parking.EF project), that should create everything for you, including some seed data if I don't remember wrong, you may also want to check in the connection string in the appsettings.json to make sure the database will be created where you want it.

This is a tutorial in case you are not familiar with what I'm mentioning above, but again it uses standard entity framework so all the usual rules apply.

https://www.tektutorialshub.com/entity-framework-core/ef-core-migrations/

**Comment by iambernics** [comment]
Hey Paulo!

Thanks, works fine! :)

We have totally same issue with the limited parking space as you described in the readme.
This was the reason why I checked the similar projects in GitHub.

On the first look, longer period than the current date is the only missing function to our use-case.
Can I fork the Project with highlighting your name (original, contact..etc)?

Regards,
Gabor

**Comment by PauloFDO** [comment]
use it on any way you want, if you feel like putting my name anywhere or letting me know where is being used (Paulo Ferreira De Oliveira) I will update my open source contribution field in my CV but really no need to worry about it. I would actually be interested on seeing your updates if you are happy to share once you finished with it, I haven't touched this in a very long time, and I would code it differently now after working with 2 more companies that provided me with more experience.

On this company the parking space were daily, which means that everyday people needed to book a parking space, the only exception are parking spaces that always belonged to someone (mostly founders), they could still free that parking space any time they wanted for anyone else to use, but everything is very specific for the specific needs of my company at the time, I'm aware that they also improved this app greatly since I left, this is what I did as a prototype and shared it with them and shortly after, Covid started, so parking space suddenly was not a problem anymore... But my boss did mention recently that they updated it to use the same code to book desks now that they use a hot desk approach in the office.

Let me know if I can help with something.

**Comment by PauloFDO** [comment]
just to clarify:

Normal users can only book a spot on the day they need it (by clicking on the spot square of the main screen).

Users that own a spot can manage that specific spot in advance.

Administrator can control any spot at any day, and only them can access the administration screen that allows them to do so.

If I don't remember wrong administrators can also book on behalf of clients, and sometimes clients would come for meetings on specific times, those clients are obviously not users so we can call them whatever we want and book way in advance
